name: Build Docker

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: choice profile
        options:
          - main
          - dev
          - test

env:
  AWS_REGION: ap-southeast-1

jobs:
  ops_build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::818052344024:role/myx-github-actions-role
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      


      - name: Get tag
        run: |
            echo ${{ steps.get_version.outputs.VERSION }}

      - name: Get current date
        shell: bash
        run: |
            echo "TIME_TAG=$(TZ=":Asia/Shanghai" date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: main branch
        if: ${{ github.event.inputs.env == 'main' }}
        run: |
          cd demo && pwd && ls -l &&\
          echo 'main'-${{ steps.get_version.outputs.VERSION }}
          # echo 'main'-${{ env.TIME_TAG }}
          
      - name: dev branch
        if: ${{ github.event.inputs.env == 'dev' }}
        run: |
          echo "DEV"-${{steps.meta.outputs.tags}} 
          echo ${{ github.event.inputs.env }}
