name: Build Docker

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: choice profile
        options:
          - main
          - dev
          - test

jobs:
  ops_build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872871084444:role/GitHubAction-AssumeRoleWithAction
          aws-region: ap-southeast-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Get current date
        shell: bash
        run: |
            echo "TIME_TAG=$(TZ=":Asia/Shanghai" date +'%Y%m%d%H%M')" >> $GITHUB_ENV
  
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: demo
          IMAGE_TAG: ${ TIME_TAG }
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get tag
        run: |
            echo ${{ steps.get_version.outputs.VERSION }}

      - name: main branch
        if: ${{ github.event.inputs.env == 'main' }}
        run: |
          echo 'main'-${{ steps.get_version.outputs.VERSION }}
          
      - name: dev branch
        if: ${{ github.event.inputs.env == 'dev' }}
        run: |
          echo "DEV"-${{ steps.meta.outputs.tags }} 
          echo ${{ github.event.inputs.env }}
